### PR TITLE
Replace `performTest` call with `performSelector` when calling `beforeAll` and `afterAll` methods.

### PR DESCRIPTION
**Pull request by ExtremeMan**
To fix the issue https://github.com/kif-framework/KIF/issues/524.

### CODE REVIEW

**Comment by phatmann** [comment]
I tested this change out to see if the logging changed when a failure in `beforeAll` occurred. The good news is that the logging is as good or even better.

Here is the log using `performTest`:

````
Test Suite 'AccessibilityIdentifierTests' started at 2015-03-10 18:50:50 +0000
Test Case '-[AccessibilityIdentifierTests beforeAll]' started.
/Users/tony/Documents/src/pull-requests/KIF/KIF Tests/AccessibilityIdentifierTests.m:20: error: -[AccessibilityIdentifierTests beforeAll] : The step timed out after 10.00 seconds: Could not find view matching: accessibilityIdentifier == "NOPE"
Test Case '-[AccessibilityIdentifierTests beforeAll]' failed (10.096 seconds).
/Users/tony/Documents/src/pull-requests/KIF/KIF Tests/AccessibilityIdentifierTests.m:20: error: AccessibilityIdentifierTests : Test suite stopped on fatal error: The step timed out after 10.00 seconds: Could not find view matching: accessibilityIdentifier == "NOPE"
/Users/tony/Documents/src/pull-requests/KIF/KIF Tests/AccessibilityIdentifierTests.m:20: error: AccessibilityIdentifierTests : Test suite stopped on fatal error: The step timed out after 10.00 seconds: Could not find view matching: accessibilityIdentifier == "NOPE"
Test Case '-[AccessibilityIdentifierTests afterAll]' started.
Test Case '-[AccessibilityIdentifierTests afterAll]' passed (0.000 seconds).
Test Suite 'AccessibilityIdentifierTests' failed at 2015-03-10 18:51:00 +0000.
   Executed 0 tests, with 1 failure (1 unexpected) in 0.000 (10.105) seconds
Test Suite 'KIF Tests - XCTest.xctest' failed at 2015-03-10 18:51:00 +0000.
   Executed 0 tests, with 1 failure (1 unexpected) in 0.000 (10.106) seconds
Test Suite 'Selected tests' failed at 2015-03-10 18:51:00 +0000.
   Executed 0 tests, with 1 failure (1 unexpected) in 0.000 (10.108) seconds
````

Note that `beforeAll` is incorrectly identified as a test case. Also note that `afterAll` is called, which seems questionable since `beforeAll` has failed and the state of the app is unknown

Here is the log using `performSelector`:

````
Test Suite 'AccessibilityIdentifierTests' started at 2015-03-10 18:49:50 +0000
/Users/tony/Documents/src/pull-requests/KIF/KIF Tests/AccessibilityIdentifierTests.m:20: error: AccessibilityIdentifierTests : Test suite stopped on fatal error: The step timed out after 10.00 seconds: Could not find view matching: accessibilityIdentifier == "NOPE"
/Users/tony/Documents/src/pull-requests/KIF/KIF Tests/AccessibilityIdentifierTests.m:20: error: AccessibilityIdentifierTests : Test suite stopped on fatal error: The step timed out after 10.00 seconds: Could not find view matching: accessibilityIdentifier == "NOPE"
Test Suite 'AccessibilityIdentifierTests' failed at 2015-03-10 18:50:00 +0000.
   Executed 0 tests, with 1 failure (1 unexpected) in 0.000 (10.081) seconds
Test Suite 'KIF Tests - XCTest.xctest' failed at 2015-03-10 18:50:00 +0000.
   Executed 0 tests, with 1 failure (1 unexpected) in 0.000 (10.082) seconds
Test Suite 'Selected tests' failed at 2015-03-10 18:50:00 +0000.
   Executed 0 tests, with 1 failure (1 unexpected) in 0.000 (10.084) seconds
````

It would be nice if the log said the error occurred in the `beforeAll` method, but it identifies the failing line in the source code so this seems like a minor issue.

I am going to merge this change in right now. Great work, @ExtremeMan!

**Comment by LegNeato** [comment]
Yay! :beers:

**Comment by pmdigregorio** [comment]
@phatmann Woooow!!! It would be great to release a version with this fix. Many project are waiting for it =). Thanks @ExtremeMan & @phatmann !!

**Comment by jmig** [comment]
:smile:

**Comment by phatmann** [comment]
As soon as we get #582 merged I will release a new version.

**Comment by ExtremeMan** [comment]
Thanks @phatmann for doing a proper testing on KIF side!

**Pull request merged**
