### PR TITLE
Adding long press drag and drop support

### PR DESCRIPTION
**Pull request by mikelupo**
@phatmann. This sort of works. I need some help getting the drag to work accurately. It does drag, but it "misses" the target.
See DraggingTests.m for a working example. 

Thanks in advance

### CODE REVIEW

**Comment by mikelupo** [comment]
@phatmann bump. 
Thanks,
Mike

**Comment by phatmann** [comment]
Sorry, I have been very busy lately. I will give KIF some more love next week.

**Comment by mikelupo** [comment]
No worries Tony. I realize that with XCode 7 coming out and all that your attention must be turned to keeping KIF viable. 
Thanks for what you do.


Regards,
Mike




-----Original Message-----

**Comment by phatmann** [comment]
@mikelupo, can you please contact me directly at thephatmann@gmail.com? Thanks.

**Comment by phatmann** [comment]
@mikelupo, should we give this PR another shot or give up?

**Comment by fangmobile** [comment]
any update? is there any other options to drag and drop?

**Comment by phatmann** [comment]
@fangmobile Neither @mikelupo or I could get this to work properly. Have a crack at it!

**Comment by justinseanmartin** [comment]
Going to close this, work on it seems to have been abandoned.

**Pull request closed without merging**
