### PR TITLE
tableview search method optimization

### PR DESCRIPTION
**Pull request by LWX124**

### CODE REVIEW

**Comment by mikelupo** [comment]
Hi @LWX124, Thank you for your PR.
Are you aware of this? #1020 I fear that your optimization might bring the "Attempt to dequeue multiple cells for the same index path crash" back.

**Comment by justinseanmartin** [comment]
Can you explain a little bit about what problem you're seeing and what you're trying to accomplish with the change? That will help a lot in evaluating the PR. Thanks!

**Comment by LWX124** [comment]
> 
[Uploading QQ20180816-143310-HD.mp4.zip…]()
Some tests like this. Cell can't be loaded and always splashing while trying to find view

**Comment by LWX124** [comment]
I've send u an email with our recorded video.

**Comment by justinseanmartin** [comment]
I saw the video, thanks for sending it. It looks to be an issue potentially specifically with large table views and possibly the video elements they contain or maybe due to the variable cell height?

@LWX124 - The fix that you provided here fully resolves the issue for you? If so, why decline the PR? Do you not want to go forward with the change?

Both changes seemed reasonable:
* Make the key window always be the first one searched (via reverseObjectEnumerator in `UIApplication-KIFAdditions.m`)
* Only call `scrollRectToVisible:` once per section. 
  * I'm not even sure why that is even necessary at all on a per-section basis, because it will immediately after `scrollToRowAtIndexPath:`. 
  * @mikelupo - do you know if/why the `scrollRectToVisible:` call for the section is necessary?

**Comment by LWX124** [comment]
The fix seems to work well for my case, but it may cause other new issues. KIF works very well for our project before updating, I'm afraid that maybe some commit have conflict with our project. I'm trying to find the real reason and make another PR.

**Comment by justinseanmartin** [comment]
I'm guessing that all the scrolling that is being done in the changes to fix #1007 is expensive and is causes KIF to become very sluggish with your long list of table view cells containing live videos.

**Pull request closed without merging**
