### PR TITLE
Remove test host reference

### PR DESCRIPTION
**Pull request by jberkel**
Possible fix for #650

### CODE REVIEW

**Comment by phatmann** [comment]
Thanks for researching this and coming up with a clean solution.

**Comment by jberkel** [comment]
i keep getting emails from xcodeserver about failing builds – any way to switch this off?  
"Integration #46 of integration tests nightly finished with 1 error."

**Comment by phatmann** [comment]
I get the same darn emails and I cannot figure out how to stop them. Clearly some issue with the Travis/Github integration.

**Comment by bnickel** [comment]
Welcome to the club. Someone has set up set up an Xcode bot and set up their build to keep pulling KIF's `origin/master`. (Does Cocoapods `:head` do this?)  It'll eventually go away when the build gets fixed and you fall out of the committers list.

If you can see other committer addresses in the email, I recommend complaining to them about their email notification config.  If it's just ServerName.local then that just sucks.

**Pull request merged**
