### PR TITLE
Bitcode error on Xcode 7 and OSX 10.11

### PR DESCRIPTION
**Pull request by anas10**
Possible fix for issue #734

### CODE REVIEW

**Comment by beatrichartz** [comment]
+1 KIF does not build with Carthage unless Bitcode is disabled

**Comment by mikelupo** [comment]
@anas10 ,
I made a fix to the .travis.yml build script that will enable your change to compile. Can you rebase your change against upstream/master and then re-push? This way the parent to your change contains the fix.

**Comment by mikelupo** [comment]
@phatmann this is still failing to build. Is it because of the code contained in this change or is it just travis being travis?

**Comment by phatmann** [comment]
I have seen Travis fail when making README changes :-(

If Travis passes that is nice and I can merge, but when it fails I have to decide how to handle it. For small changes where the submitter has run the tests locally on their machine or otherwise verified it, I will go ahead and do the merge. For larger changes or changes that concern me, I will run the tests locally.

For this change I would merge it now, since it is small. was verified by the submitter...and is actually important to keep KIF working! :-)

**Comment by mikelupo** [comment]
@phatmann Thanks. Merging!

**Comment by anas10** [comment]
Didn't had time to rebase, you were to fast for me :) For changes like this it's ok though.  Thanks!

**Pull request merged**
