### PR TITLE
SPM Integration Fixes

### PR DESCRIPTION
**Pull request by pbartolome**
This PR fixes the issues commented on https://github.com/kif-framework/KIF/issues/1212

- Public headers have been symlinked to a `include` folder, which is listed in the `publicHeaders` section of the `Package.swift`. Now clients can access classes that are inside the KIF module.
- No more warnings on the umbrella header
- Add `IOKit` as a requirement when using SPM
- Added a new sample project `SPMIntegration` which uses SPM to add `KIF` to a Swift test target

### CODE REVIEW

**Review by dostrander — COMMENTED** [review]
Looks good. The only thing is can we move the SPMIntegration project into the root folder instead of the `Documentation/Examples` folder?

Thanks for doing this

**Comment by pbartolome** [comment]
There was an existing failing tests `testSelectingCurrentDateTime`... interestingly it was failing at a specific time (if executed around 12pm). There was an issue in the test actor using the picker, incorrectly adding 12 when the time was 12pm to make it 24h format. I pushed a fix and a test so it doesn't add 12 when the time is 12pm.

```
10am + 0 = 10 OK
11am + 0 = 11 OK
12pm + 12 = 24 INCORRECT, should be 12pm + 0 = 12
1pm + 12 = 13 OK
2pm + 12 = 14 OK
```

**Review by dostrander — APPROVED** [review]

**Comment by kenji21** [comment]
👍🏻 (remember that a "server" tag needs to be released to make this available via SPM)

**Comment by pbartolome** [comment]
Thanks for merging it, any plans to release a new version with the changes?

**Comment by dostrander** [comment]
Yeah will do this week

**Comment by kikeenrique** [comment]
I just miss an updated readme reflecting the support/instructions for SPM.

**Comment by dostrander** [comment]
Released a new version.

**Pull request merged**
