### PR TITLE
Possibly fix for XCode 6.3 sendEvent BAD_ACCESS 

### PR DESCRIPTION
**Pull request by sebbean**
replaced UIApplication sendEvent: with touchesBegan/touchesEnded

### CODE REVIEW

**Comment by phatmann** [comment]
@sebbean, can you please check in the test of the changes?

I would feel more comfortable with this PR if we could find an explanation of what is causing the #574 crash, so we can verify that this solution makes sense. If I have time I will dig in on this.

**Comment by phatmann** [comment]
I am also looking at #582 to see which solution seems better.

**Comment by phatmann** [comment]
I took a look at #582. At least we now understand the cause of the crash. #582 solves the issue but requires a lot of extra code. The solution proposed in this PR skirts the whole issue by avoiding sending events, but it means that KIF is not actually simulating taps any more. I am afraid that this will break people's tests, but perhaps someone could convince me otherwise.

**Comment by sebbean** [comment]
Note: this fix does not work for swipes or long presses

**Comment by phatmann** [comment]
@sebbean I misunderstood your earlier comment, I thought you had fixes for swipes and long presses on your machine. If you do not, then we need to go with #582. I am going to close out this PR. Please re-open if you find way to make a complete fix and we have not yet merged #582.

**Pull request closed without merging**
