### PR TITLE
Fixing broken table scrolling

### PR DESCRIPTION
**Pull request by harleyjcooper**
When attempting to tap offscreen table elements, after `[tableView scrollToRowAtIndexPath:indexPath atScrollPosition:UITableViewScrollPositionNone animated:animationEnabled]` is called, the scrolling never actually occurs before the call to `[tableView cellForRowAtIndexPath:indexPath]`, which will always return `nil` for offscreen table cells. A yield could be inserted in there, but for large tables, that would be an enormous amount of time.

The spinning of the runloop after that block only allows the final call to `scrollToRowAtIndexPath` to be executed, so the code will only succeed if the cell is in view initially, or it's in the final scrolled section in the table. This code, as it was, would never succeed if the cell being sought was above the initially scrolled area of the table.

Switching the `scrollToRowAtIndexPath` call to `[tableView scrollRectToVisible:sectionRect animated:NO]` is more instantaneous, requires no yield, and works for cells above AND below the currently-scrolled portion of the table.

Plus, the final call to `[tableView scrollRectToVisible:initialPosition animated:NO]` will succeed in moving back to the initial position for all cases, essentially instantaneously.

### CODE REVIEW

**Comment by justinseanmartin** [comment]
Overall LGTM as long as you update the PR description to explain what you're doing and why.

**Comment by dflems** [comment]
@justinseanmartin Can you cut a new version once this is merged?

**Comment by justinseanmartin** [comment]
Yea, @dflems - were you able to test the change, did it work for you all?

**Comment by harleyjcooper** [comment]
@dflems We've released KIF 3.7.6 - https://github.com/kif-framework/KIF/releases/tag/v3.7.6

**Comment by dflems** [comment]
@justinseanmartin Looking good. Previously ~40 tests were failing/flaking and now it's down to two (looks like its for other reasons than the scrolling though). I'll follow up once we diagnose those.

**Pull request merged**
