### PR TITLE
Set default test configuration to Debug from Coverage

### PR DESCRIPTION
**Pull request by justinseanmartin**
I don't believe that anyone is using the files for anything useful at the moment and it makes a bunch of noise in the console logs when running tests. I switched the default project config to be `Debug` and deleted the checked in gcda file.

### CODE REVIEW

**Comment by phatmann** [comment]
@bnickel: are you ok with this change?

**Comment by justinseanmartin** [comment]
There may be some other place where this is being used that I didn't realize. From my perspective, it just generates noise in the console logs and dirty files on the the file system when running tests.

**Comment by justinseanmartin** [comment]
Ok to merge?

**Comment by mikelupo** [comment]
I think we're waiting to hear from @bnickel on this change

**Comment by phatmann** [comment]
I will merge the change since we have not heard any objections from @bnickel. We can always revisit this as appropriate.

**Pull request merged**
