### PR TITLE
Add swipeViewWithAccessibilityIdentifier method.

### PR DESCRIPTION
**Pull request by mikelupo**
Test cases are also added for swipe up, down, left, right.
view identification takes place on the accessibility identifier
rather than the accessibilityLabel attribute.

### CODE REVIEW

**Comment by mikelupo** [comment]
@phatmann, I considered that you'd want these tests to be embedded within the IdentifierTests class.
IMHO these fit best into the GestureTests class as GT puts the client into the proper context by way of:
- (void)beforeAll
{
    [tester tapViewWithAccessibilityLabel:@"Gestures"];
}
Thanks,
Mike

**Comment by mikelupo** [comment]
Noob mistake: Pressed "Close and Comment" button rather than just "Comment". Won't make that mistake again. Sorry if anyone got spammed.

**Comment by mikelupo** [comment]
Hi @phatmann any chance this can get vetted? I'd like to take it into use but am holding off depending on if you'll accept it or not.

Regards,
Mike

**Comment by phatmann** [comment]
Hi @mikelupo. Thanks for putting this together. A few things:

* See #614. We should use `swipeAccessibilityElement` for your implementation.
* All the methods that use accessibilityIdentifiers are supposed to go in KIFUITestActor-IdentifierTests.

**Comment by mikelupo** [comment]
I made the second commit (locally) with your asked changes. I then squashed them then force pushed. I'm not sure if I did it correctly. If not, then I'll just close this pull request and do it again from scratch in one clean commit. Let me know...
Thanks!

**Comment by phatmann** [comment]
@mikelupo, unfortunately now there are 12 commits in the PR :-(

**Comment by mikelupo** [comment]
Ok, I'll resubmit as a fresh new one. I suspect it's my git "prowess" that led to this. :)

**Pull request closed without merging**
