### PR TITLE
Rename system macro to kif_system

### PR DESCRIPTION
**Pull request by kkodev**
This addresses issue #834

### CODE REVIEW

**Comment by mikelupo** [comment]
Two things. 
1) the change to fix the Operator in a test needs to be in a separate PR. Otherwise, this change looks fine.
2) I defer to @phatmann and @bnickel for the commit that renames system to kif_system.

**Comment by kkodev** [comment]
Makes perfect sense. I extracted the operator change and will open separate PR

**Comment by phatmann** [comment]
Obviously changing `system` to `kif_system` is a breaking change. If we are going to break clients, I would rather get rid of the macros entirely and use functions or methods instead. Then the pain of migrating is worth it.

**Comment by justinseanmartin** [comment]
This is also being taken care of by #988

**Pull request closed without merging**
