### PR TITLE
fix typist to work on device with split keyboards

### PR DESCRIPTION
**Pull request by brightredchilli**
This pull request fixes kiftypist behaviour on device with split keyboards. The manifestation was that enterTextIntoFirstResponder will fail when on device with split keyboard, because the UIKeyboardWillShowNotification never gets fired under those circumstances.

### CODE REVIEW

**Comment by phatmann** [comment]
Looks good, nice work.

**Comment by brightredchilli** [comment]
@phatmann, any chance we can make a tag and cocoapods for this? It's really too bad that there is not an automated way to do this. We use KIF on our project heavily and would benefit from more granular updates. I could do it too but I would need pull access to the repository.

**Comment by phatmann** [comment]
@brightredchili, is there any reason you cannot use `:head` in your Podfile?

In the meantime, let me review the latest commits and see if another release is appropriate. I usually like to resolve all the pull requests "in progress" first.

**Comment by brightredchilli** [comment]
The problem with using 'head' or 'master' is that 'pod update' will move the dependencies of KIF forward, when I really want just 3.2.xx, for example. Somewhat of an annoyance but we can work around it

**Comment by TBonnin** [comment]
I think you can specify a specific commit `:commit => '082f8319af'`

**Comment by phatmann** [comment]
I have just pushed 3.2.1 with this fix in it.

**Pull request merged**
