### PR TITLE
Added two finger tap gesture

### PR DESCRIPTION
**Pull request by brightredchilli**
This adds a two finger tap gesture and associated tests.

I also removed gesture recognizers from the tests once they were done in case they caused side effects with future tests.

### CODE REVIEW

**Comment by brightredchilli** [comment]
Also added rotation gestures that I roughly tested...would be glad if I had some people help me testing this before it gets merged in. I feel pretty confident about two finger tap and if it helps speed things up I'd like to merge that in first.

**Comment by phatmann** [comment]
@brightredchilli, these look like good additions. Unfortunately, you reverted all your changes in the twofingertap branch. Was your intent to leave the two finger tap change in?

**Comment by brightredchilli** [comment]
The build is passing locally for me but failing the Travis check, although the tests that are failing have seemingly nothing to do with my changes. I am currently debugging.

**Comment by brightredchilli** [comment]
@phatmann There's something non-deterministic about the travis failures, which worries me. I have changed nothing about these two commits, other than the fact that I've rebased onto master - which didn't seem to contain any fixes for tests.

I'm confident the failures were not due to these changes, since they were failures testing specific ui controls, and I did not touch any underlying tapping code. I will raise an issue for one that I could deterministically get to fail on my machine.

**Comment by brightredchilli** [comment]
@phatmann, is there any items I can help to make this code review go through? Thanks!

**Comment by phatmann** [comment]
@brightredchilli, I will merge now. I was under the false impression you were still working on this.

**Pull request merged**
