### PR TITLE
UIPanGestureRecognizer velocity test cases

### PR DESCRIPTION
**Pull request by kdlogen**
I implemented 4 new test cases for testing the UIPangestureRecognizer`s velocity value.

### CODE REVIEW

**Comment by phatmann** [comment]
I always like to have more tests, thanks!

**Comment by kdlogen** [comment]
Your welcome! ;)

We wanted to mention that the tests didn't work if we requested the UILabel with method ```waitForViewWithAccessibilityLabel:``` (we used ```waitForTappableViewWithAccessibilityLabel:```). As we noticed this behaviour happens because somehow the gesture recognizer can't initialize everything before the test case starts. If you make an extra wait with ```CFRunLoopRunInMode``` (~0.1 sec!?) method call before sending every touch event that will work with ```waitForViewWithAccessibilityLabel:```(```UIView+KIFAdditions.h - dragPointsAlongPaths:``` method).

p.s.: You can try it by running only one older swipe test case. The test case should fail!

Does it have any sense? What do you think about it?

**Comment by phatmann** [comment]
@kdlogen, I do not understand the issue you mention above. Why would the gesture recognizer prevent `waitForViewWithAccessibilityLabel:` from working? Did you mean to say that `waitForTappableViewWithAccessibilityLabel:` was failing?

**Comment by kdlogen** [comment]
If you run a single test case (for example GestureTests.m -> testSwipingLeft) then that fails. You can try out waiting for view with method *[tester waitForViewWithAccessibilityLabel:@"Swipe Me"];* but that isn't enough, you should use *[tester waitForTappableViewWithAccessibilityLabel:@"Swipe Me"];* method.
I don't know exactly what is the main difference between those methods, but it seams the system can`t  initialize the gesture recognizers before swiping on the view.

You can find a solution in pull request #669.

**Comment by phatmann** [comment]
@kdlogen Thanks for the fix.

**Pull request merged**
