### PR TITLE
Add identifier test: isElementWithAccessibilityIdentifierVisible

### PR DESCRIPTION
**Pull request by mikelupo**
Add the ability to test whether an element is visible on the screen based on the accessibilityIdentifier. This pull request attempts to add that.

### CODE REVIEW

**Comment by phatmann** [comment]
I am open to this change, but the method name should match the form used in `KIFUITestActor-ConditionalTests`. Take a look.

**Comment by mikelupo** [comment]
@phatmann. Thank you for your comments.

Sorry it took me so long to get back to this. I have committed the change based on your recommendation. 
Please let me know if I need to make any other changes.

Regards,
Mike

**Comment by phatmann** [comment]
The method name is good now. But there are two things to take care of, if you would:

1. Add a unit test in AccessibilityIdentifierTests.m
2. Squash all the commits

Also note that you created this PR from your master branch, so don't make any commits to your master branch until I merge your changes, otherwise the new commits will sneak in. In the future I recommend making a new branch for each PR to avoid this problem.

Thanks!

**Comment by mikelupo** [comment]
@phatmann , Thanks for your comments. I have made the changes you have requested.
Let me know if anything else is needed.

**Comment by phatmann** [comment]
Thanks!

**Pull request merged**
