### PR TITLE
rename framework target to just 'KIF' so it can coexist with Cocoapods

### PR DESCRIPTION
**Pull request by simX**
We're exploring Carthage support in our app, and it gives us a lot of benefits now, but we can't drop iOS 7 support yet, which means we still have to support Cocoapods.

With the current Carthage support merged into KIF, you have to use the following syntax to import KIF header files: #import \<KIFFramework/KIF.h\>.  Unfortunately, if you use that syntax in source code that is also built via Cocoapods, the Cocoapods build fails.

In this pull request, I propose changing the name of the built product to simply "KIF.framework".  This is simpler and cleaner.  In addition, it allows you to use this syntax: #import \<KIF/KIF.h\>, which works for both Carthage and Cocoapods, regardless of which dependency manager you're using.  That way, you don't have to use any ugly macros to support both.

This pull request leaves the scheme and target names at "KIFFramework" (contrary to the somewhat inaccurate commit message), so that it's still understandable what that target and scheme are for.  It's just changing the product name to "KIF", which results in the built framework product being named "KIF.framework".

In addition, this pull request includes \<KIF/KIFUITestActor-IdentifierTests.h\> in the public header so that those of us that need to use accessibility identifiers can do so with the framework target.

### CODE REVIEW

**Comment by simX** [comment]
cc-ing @lottadot and @phatmann since they worked on the original Carthage pull request: https://github.com/kif-framework/KIF/pull/624

**Comment by phatmann** [comment]
Seems like a good change. I like the clean solution to a potentially thorny problem.

**Comment by phatmann** [comment]
@simX, unfortunately this PR needs rebasing on master. Can you do that? If not I can do it.

**Comment by simX** [comment]
Rebased, but had to create a new pull request: https://github.com/kif-framework/KIF/pull/657

**Pull request closed without merging**
