### PR TITLE
Added KIFUITestActor-IdentifierTests to KIF-Header-File

### PR DESCRIPTION
**Pull request by LordNali**
Added KIFUITestActor-IdentifierTests to KIF-Header-File

### CODE REVIEW

**Comment by phatmann** [comment]
This header is purposely not part of KIF.h, because it is brought in via a CocoaPod subspec. Can you explain what is motivating you to make this change?

**Comment by LordNali** [comment]
Okay, I didn't know that - we tried to use Carthage to integrate KIF in our Project (like for all our other Frameworks), but unfortunately that doesn't work as expected. Then we included the KIF Project manually / from Source and that works fine.

I'm a bit confused, since your ReadMe list 'Installation (from GitHub)' as an Install-Option - are we're the only ones using this option with Swift and AccessibilityIdentifier Tests?!

**Comment by phatmann** [comment]
Can't you just include the Identifier test header manually alongside KIF.h?

**Comment by LordNali** [comment]
Sure - I just added the Identifier Test header to our Objective-C bridging header. So no need to merge this PR, but maybe this should be mentioned in the ReadMe.

**Comment by phatmann** [comment]
Sounds good. If you feel like updating the README please go for it, otherwise I can do so. Thanks.

**Comment by LordNali** [comment]
I would kindly ask you to update the ReadMe - I'm not sure my English fits the purpose here. Furthermore I would recommend that you implicitly make a Section for "Swift-Users" and point them directly to the Testable-Swift Example: In our case it was easy to configure our Test Target by comparing our Project with your Example Project side by side.

**Comment by phatmann** [comment]
Done!

**Pull request closed without merging**
