### PR TITLE
Add fix for a case where accessibility element frame was zero

### PR DESCRIPTION
**Pull request by steipete**
We ran into this and I wanted to open a PR in case anyone else sees this.

Probably misses a KIF test case and more details - ping me if you see or know about a similar issue.

### CODE REVIEW

**Comment by phatmann** [comment]
I would like to understand what broke to cause this problem and in which testing scenarios you run into this issue. If we are working around a bug in UIAccessibility, then this is a fine fix, but if we are working around a bug in KIF itself, then we should fix the root cause.

**Comment by steipete** [comment]
Agreed; need to do more digging here to see what broke. Will follow up.

**Comment by fritzsche91** [comment]
As I have observed **similar issues** for srolling/swiping, this is potentially related to: https://github.com/kif-framework/KIF/pull/869

If you need any more information on this, feel free to contact me.

**Comment by justinseanmartin** [comment]
The fix in #869 was merged and haven't heard other reports of this in over a year. Closing this issue out.

**Pull request closed without merging**
