### PR TITLE
Fix pull to refresh

### PR DESCRIPTION
**Pull request by wanbok**

### CODE REVIEW

**Comment by phatmann** [comment]
This PR still has the Testable Swift commits in it. Now that I have merged your other PR, rebasing the `fix-pull-to-refresh` branch on the upstream master branch should fix this.

**Comment by wanbok** [comment]
@phatmann I have rebased this PR. :)

**Comment by phatmann** [comment]
The changes look good. Can you please squash the 4 commits into one commit? Then I can merge it. Thanks for your efforts.

**Comment by wanbok** [comment]
@phatmann :)

**Pull request merged**
